name: tests

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

jobs:
  ci:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: composer:v2
          coverage: none

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install Node Dependencies
        run: npm ci

      - name: Build Assets
        run: npm run build

      - name: Install PHP Dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Setup .env
        run: |
          cp .env.example .env
          php artisan key:generate
          php artisan config:clear

      - name: Set DB config
        run: |
          sed -i 's/DB_CONNECTION=.*/DB_CONNECTION=pgsql/' .env
          sed -i 's/DB_HOST=.*/DB_HOST=127.0.0.1/' .env
          sed -i 's/DB_PORT=.*/DB_PORT=5432/' .env
          sed -i 's/DB_DATABASE=.*/DB_DATABASE=test_db/' .env
          sed -i 's/DB_USERNAME=.*/DB_USERNAME=postgres/' .env
          sed -i 's/DB_PASSWORD=.*/DB_PASSWORD=password/' .env

      - name: Run Migrations
        run: php artisan migrate --force

      - name: Run Tests
        run: ./vendor/bin/pest
